### ISSUE TITLE
404 error on user map

### ISSUE THREAD

**Issue by vpicavet** [qgis/QGIS-Django#107]
The following address gives a 404 error : https://plugins.qgis.org/community-map/

Furthermore, the link to file a ticket on the 404 web page links to the old repository : http://hub.qgis.org/projects/qgis-django

**Comment by sumandari** [comment]
@vpicavet if I'm not mistaken, the ticket is https://issues.qgis.org/issues/9930

This url path is disabled with a comment tag, and there's no module named 'user_map'
https://github.com/qgis/QGIS-Django/blob/a5023d84463fb64805b65873de5866fd2a274c55/qgis-app/urls.py#L37

@timlinux would you please advise about this. Thank you

**Comment by timlinux** [comment]
@sumandari just hide the menu option for now until we can get a working map in place

**Comment by timlinux** [comment]
For now I removed it from the menu

![image](https://user-images.githubusercontent.com/178003/100433347-de6d5e00-3092-11eb-957f-24935945132a.png)


We can add it back later when the map is implemented

![image](https://user-images.githubusercontent.com/178003/100433395-ec22e380-3092-11eb-8bb2-62a40824edf2.png)
