### ISSUE TITLE
Sort error on styles page

### ISSUE THREAD

**Issue by vpicavet** [qgis/QGIS-Django#108]
Steps to reproduce : 
- Go to https://plugins.qgis.org/styles/
- sort the style list thanks to one of the arrows on top of the style list
- click on "page 2"

Expected result : the next page of styles, sorted

Actual result : the second page of styles, unsorted

**Comment by sumandari** [comment]
@vpicavet 
Thank you for your information. 
This issue has been fixed by #104. However, the deployment time is waiting for confirmation.
cc @timlinux @dimasciput
