### ISSUE TITLE
We need to completely document backup deployment on rancher, hetzner

### ISSUE THREAD

**Issue by timlinux** [qgis/QGIS-Django#111]
Please create a detailed README explaining how to backup, deploy, deploy updates

![image](https://user-images.githubusercontent.com/178003/99949715-65f55d00-2d73-11eb-929c-966a7b2877a7.png)

Also common tasks like configuring site settings for email recipients, sending etc.

Please make sure not to leak any sensitive information.

**Comment by sumandari** [comment]
@dimasciput would you please assist me on this since I have no experience to do those things yet. Many thanks :smiley:
