### ISSUE TITLE
Add some checks on the metadata.txt

### ISSUE THREAD

**Issue by Gustry** [qgis/QGIS-Django#117]
Related to the nice work from @sumandari in #116 
I think we could have more checks in the validation process.

For instance, in the `metadata.txt`:
* bug tracker
* plugin home page
* code repository 
should have valid URL (not a 404 for instance). There is a few times where we can't contact plugins author.

I'm sure that @NyakudyaA has some others idea to check ? ;-)

**Comment by NyakudyaA** [comment]
@sumandari Here is an example of bad metadata.txt

![Screenshot 2020-12-03 at 13 06 53](https://user-images.githubusercontent.com/2510900/101002358-a79eb880-3568-11eb-903a-d3eb92c85f3a.png)

Besides the validation how can we also portray the message that we need a valid
* bug tracer
* plugin home page
* code repository.

Other checks we need to have that people need to:
* A short description of what the plugin does. Even for plugins that are not geared for the English speaking community, we need to have the description
* Check for external libs - We do not want plugins packaged with external libs
* For plugins that are being updated we need users to populate a proper changelog in metadata.txt

Just on a side note - Sometimes plugin authors give a working plugin home page but it is unrelated to what the plugin actually does

**Comment by timlinux** [comment]
@sumandari maybe start with the simple cases:

 We need a valid:

    bug tracer
    plugin home page
    code repository.

@NyakudyaA and @Gustry I don't know if there is a good way we can check the other items like external lib checking and changelog population. If you have ideas about this, please share the logical framework that you think @sumandari should follow so she can implement that.

**Comment by NyakudyaA** [comment]
> @sumandari maybe start with the simple cases:
> 
> We need a valid:
> 
> ```
> bug tracer
> plugin home page
> code repository.
> ```
> 
> @NyakudyaA and @Gustry I don't know if there is a good way we can check the other items like external lib checking and changelog population. If you have ideas about this, please share the logical framework that you think @sumandari should follow so she can implement that.

@sumandari You can just check if the links are valid but are not the basic links provided by the plugin builder ie
![plugin-builder](https://user-images.githubusercontent.com/2510900/107489059-dc467600-6b90-11eb-857c-4c51cdde86f1.png)

For the code repository, I would just add an extra check to see if the repo is a public repo or not and reject it if the repo is a private one

**Comment by Gustry** [comment]
Yes, that's would be cool, checking that 
* the bug tracker is indeed **not** `http://bugs`
* the repo is not `http://repo`
* the homepage is not `http://homepage`

And raise a graphical warning if these given URL are not valid with an HTTP request ?  (not a 4XX or 5XX HTTP return code)
Because I don't want a plugin to fail uploading if the website is temporarily down for instance.

We can think about other checks too.

**Comment by sumandari** [comment]
the fix has been deployed. I will close this for now
