### ISSUE TITLE
add a feature: sharing GPKG file. 

### ISSUE THREAD

**Issue by timlinux** [qgis/QGIS-Django#118]
A GeoPackage should come with:

- a proper screenshot
    - description explaining what project demonstrate
    - filesize < 1 mb

**Comment by elpaso** [comment]
I must have missed something, what is this feature for? Demo projects?

**Comment by sumandari** [comment]
Hi @elpaso, this is alike styles module but for sharing small example QGIS projects (gpkg file). I believe @timlinux can explain it better

**Comment by timlinux** [comment]
Yes it is for sharing demo projects
