### ISSUE TITLE
Incorrect count of styles shown

### ISSUE THREAD

**Issue by nyalldawson** [qgis/QGIS-Django#122]
Going to https://plugins.qgis.org/styles/?page=1&& shows a header "20 records found":
![image](https://user-images.githubusercontent.com/1829991/101106101-189ea880-361b-11eb-8117-783b1e39f4da.png)

This is incorrect -- it's showing the count of records on the current page only. 

The equivalent plugin page shows the correct total count, not the current page count:

![image](https://user-images.githubusercontent.com/1829991/101106168-3835d100-361b-11eb-9603-ba75effd063a.png)

**Comment by sumandari** [comment]
Thanks for your input @nyalldawson 
This issue has been fixed by PR https://github.com/qgis/QGIS-Django/pull/104. It's waiting for deployment.

**Comment by nyalldawson** [comment]
Thanks @sumandari !

**Comment by sumandari** [comment]
fixed,  thanks.
![count_styles_all](https://user-images.githubusercontent.com/40058076/101503462-176bd380-39ad-11eb-9c4e-8e273aba8d1a.png)
