### ISSUE TITLE
Show larger thumbnails for style browsing

### ISSUE THREAD

**Issue by nyalldawson** [qgis/QGIS-Django#123]
The current way of browsing styles is not so friendly -- you get a tiny icon as the only preview of how a style looks:

![image](https://user-images.githubusercontent.com/1829991/101106261-6a473300-361b-11eb-9a5e-6dae427c8dd4.png)

This makes it hard to see if a style is worth fetching and you have to first click on the row to see a full sized preview. Eg look at the icon for Dormido Rough -- it looks like a boring solid brown fill. 

But after clicking the row you get a beautiful full sized preview, and then realize that YES! it's worth my time getting:

![image](https://user-images.githubusercontent.com/1829991/101106308-80ed8a00-361b-11eb-9abf-d168fab5df0c.png)

It would be nice to implement a large thumbnail grid view of browsing styles instead of the row based view we currently have.

**Comment by timlinux** [comment]
I think we could also add a gallery view @sumandari like Klas had in his origina mockup. Thanks for the fix @sumandari and the report @nyalldawson

**Comment by anitagraser** [comment]
@timlinux sorry for pulling out this old ticket but is there an existing issue for implementing a gallery view? (couldn't find it) 
I think a nice gallery view would make the experience much more attractive.
