### ISSUE TITLE
Uploading my Plugin

### ISSUE THREAD

**Issue by FVW-Services** [qgis/QGIS-Django#147]
I am trying to upload a plugin zip file and this is the error message gotten:

**There were errors reading the plugin package (please check also your plugin's metadata). For security reasons, the zip file cannot contain the '.git' directory**

**Comment by Gustry** [comment]
Does your zip contain the hidden `git` directory  as stated in the error message ?
Drop your ZIP attached here so we can check

**Comment by FVW-Services** [comment]
[dem_drainage_analyses.zip](https://github.com/qgis/QGIS-Django/files/5753048/dem_drainage_analyses.zip)

**Comment by Gustry** [comment]
Remove `__pycache__` folder

**Comment by Gustry** [comment]
I'm also checking your metadata at the time.
Please check URL provided.

```
homepage=http://github.com/FVW-Services/DEM_Draiange_Analyses
tracker=http://github.com/FVW-Services/DEM_Draiange_Analyses/issues
repository=http://github.com/FVW-Services/DEM_Draiange_Analyses
```

You made a typo in `Draiange`. It won't be valid.

And the correct URL
https://github.com/FVW-Services/DEM_Drainage_Analyses
is not correct as well because it needs to the source code, not the zip.

**Comment by FVW-Services** [comment]
I have effected all those changes (corrected the typo, and removed the __pycache__ folder) and also uploaded the source code "DEM_drainage_analyses.py" file.

I still can not upload my plugin here: https://plugins.qgis.org/plugins/add/

This error still shows: There were errors reading the plugin package (please check also your plugin's metadata). For security reasons, the zip file cannot contain the '.git' directory

What can I really do, practically?

**Comment by Gustry** [comment]
Attach your zip so we can understand.

@sumandari Maybe the error message needs to be improved ?

**Comment by FVW-Services** [comment]
[dem_drainage_analyses.zip](https://github.com/qgis/QGIS-Django/files/5756500/dem_drainage_analyses.zip)

**Comment by Gustry** [comment]
I honestly don't know what is wrong with the zip.
But for sure, you can remove all not necessary folder such as : 
`.idea`
`help`
`scripts`
`test`
(at least from the zip)

Also in the metadata.txt, you have duplicated lines : 
```
homepage=
tracker=
repository=
```

**Comment by FVW-Services** [comment]
does the duplication really affect it? and do you mean I should remove all those folders while uploading the plugin into QGIS?

**Comment by agiudiceandrea** [comment]
The ".gitignore" (it contains ".git" in the path string) file that is in the ".idea" folder shold be removedvin order to pass the current check

**Comment by FVW-Services** [comment]
Thank, you so much. It has been uploaded successfully. So I now wait for its approval. Thanks again.

**Comment by timlinux** [comment]
Thanks I will close this for now.
