### ISSUE TITLE
We need an API for discovering resources

### ISSUE THREAD

**Issue by timlinux** [qgis/QGIS-Django#155]
![image](https://user-images.githubusercontent.com/178003/106588815-2604e000-6543-11eb-9aad-138a41797ca6.png)

# For Listing

Should be able to add as filters:

* resource type (symbol / project / composition etc)
* resource subtype (line symbol etc.)
* keywords for search (e.g. 'Elevation') - should be case insensitive
* creator

Results should include:

* resource id
* resource creator
* number of downloads
* upload date

# For downloading

Parameter should be a resource ID

Results should include:

* resource zip

# Caching mechanism

We could do caching on client and server side

I think we should cache all the unfiltered requests so based on 

* resource type (symbol / project / composition etc)
* resource subtype (line symbol etc.)

**Comment by sumandari** [comment]
- [x] listing
- [x] downloading
- [ ] caching mechanism
