### ISSUE TITLE
New version of the plugin approved but does not appear in QGis desktop

### ISSUE THREAD

**Issue by Gui0delp** [qgis/QGIS-Django#157]
Hi,
I uploaded a new version (v1.1.1) of my plugin not long ago and it was approved, thank you for that :) But currently the plugin has no downloads because on the QGis desktop side, the update does not appear. It is likely that it is from my metadata but I am drying, can someone help me on this point or explain to me the why and how? ^^

[https://github.com/Gui0delp/french_address](https://github.com/Gui0delp/french_address)

[https://plugins.qgis.org/plugins/french_address/](https://plugins.qgis.org/plugins/french_address/)

[french_address.zip](https://github.com/qgis/QGIS-Django/files/5916843/french_address.zip)

PS: the upload of the previous version (v1.1.0) did not cause any problem

**Comment by Gustry** [comment]
Same problem as https://github.com/qgis/QGIS/issues/41336

@timlinux @dimasciput Do you have any idea related to the server maintenance last week ?

**Comment by dimasciput** [comment]
@Gustry I'm on it

**Comment by rduivenvoorde** [comment]
Not sure if we still create the xml's every 15 minutes, but if so, it could be that that process does not run?

**Comment by dimasciput** [comment]
oh no, the worker that responsible for generating the metadata is down, I'm really sorry, should be fixed now. @Gustry @rduivenvoorde @Gui0delp

**Comment by Gui0delp** [comment]
@dimasciput No problem, everything works, thank you very much :)

**Comment by Gustry** [comment]
I can confirm I can see the plugin @Gui0delp French Address v1.1.1

@Gui0delp Can you close your ticket ?

**Comment by timlinux** [comment]
> Not sure if we still create the xml's every 15 minutes, but if so, it could be that that process does not run?

In the last update we changed it to regenerate the XML cache whenever a plugin is uploaded so it is always 'current'.
