### ISSUE TITLE
Error while uploading a plugin about links

### ISSUE THREAD

**Issue by Gustry** [qgis/QGIS-Django#169]
Since #163, I'm having a issue uploading the plugin on the website.

By using qgis-plugin-ci : https://github.com/3liz/lizmap-plugin/runs/1975378326#step:8:443

```
A fault occurred
Fault code: 1
Fault string: <Fault 1: 'File upload must be a valid QGIS Python plugin compressed archive. Please provide valid url link for Bug tracker, Repository and Home page in metadata.'>
Error: Process completed with exit code 1.
```

I tried to download the ZIP manually from https://github.com/3liz/lizmap-plugin/releases/tag/3.4.1
and uploading it on the website : 

```
There were errors reading plugin package (please check also your plugin's metadata).
Please provide valid url link for Bug tracker, Repository and Home page in metadata.
```
Here, the error message, is not mentioning any compressed archive.

But I have check all links, there are all correct : 

```ini
homepage=https://docs.lizmap.com
tracker=https://github.com/3liz/lizmap-plugin/issues
repository=https://github.com/3liz/lizmap-plugin
```

I tried to change in the ZIP the link to the homepage because it's redirection from https://docs.lizmap.com to https://docs.lizmap.com/current/en/ but still not possible to upload the plugin.

@sumandari When raising the `error_check` exception, the best is to provide which URL has been wrong (homepage, or bugtracker or code repository) and if possible the possible error message.

If you have any clues why I can't upload the plugin. Last time I uploaded one was end of december : https://plugins.qgis.org/plugins/lizmap/

I have checked on a quick Python script as well, no issues : 

```python
url = 'https://github.com/3liz/lizmap-plugin'

import requests
from urllib.parse import urlparse

class ErrorCheck(BaseException):
    pass

def _check_url_link(url: str, forbidden_url: str) -> None:
    """
    Checks if the url link is valid.
    """
    error_check = ErrorCheck("Error")

    # check against forbidden_url
    is_forbidden_url = url == forbidden_url
    if is_forbidden_url:
        raise error_check

    # check if parsed url is valid
    # https://stackoverflow.com/a/38020041
    try:
        parsed_url = urlparse(url)  # e.g https://plugins.qgis.org/
        if not(all([parsed_url.scheme,  # e.g http
                   parsed_url.netloc])):  # e.g www.qgis.org
            raise error_check
    except Exception:
        raise error_check

    # Check if url is exist
    # This check will slow down the upload process.
    try:
        req = requests.head(url)
    except Exception:
        raise error_check
    if req.status_code >= 400:
        raise error_check
        
_check_url_link(url, 'http://bugs')
```

**Comment by Gustry** [comment]
Ok, I could upload the plugin by changing from

```ini
homepage=https://docs.lizmap.com
tracker=https://github.com/3liz/lizmap-plugin/issues
repository=https://github.com/3liz/lizmap-plugin
```

to

```ini
homepage=https://github.com/3liz/lizmap-plugin
tracker=https://github.com/3liz/lizmap-plugin
repository=https://github.com/3liz/lizmap-plugin
```

**Comment by sumandari** [comment]
Thanks for the detail @Gustry.
I updated the error message, and use your url value:

![image](https://user-images.githubusercontent.com/40058076/109093427-4e06ee00-7753-11eb-8dd5-14a69b27537c.png)

but I think the homepage url `https://docs.lizmap.com` should pass the check

I will provide a better error message to expose  which validation check was failed, and sort out why this url link didn't pass the check

**Comment by sumandari** [comment]
The error came from 

https://github.com/qgis/QGIS-Django/blob/dd43bcb273c3f072f99f3e245fe93abc506ee1c4/qgis-app/plugins/validator.py#L83


```
requests.exceptions.SSLError: HTTPSConnectionPool(host='docs.lizmap.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1056)')))
```

It will pass when the url using `http` instead `https`.

**Comment by Gustry** [comment]
Thanks for checking @sumandari 

Is there anything to check on our server ?
But this issue might be raised by other plugins and the check shouldn't be that strict ?
Maybe you should just `try..except` this exception and `pass` ?

**Comment by sumandari** [comment]
I add an exception: 

```
   try:
        req = requests.head(url)
    except requests.exceptions.SSLError:
        req = requests.head(url, verify=False)
```


I don't understand this question @Gustry . Can you please explain?
> Is there anything to check on our server ?

**Comment by Gustry** [comment]
> I don't understand this question @Gustry . Can you please explain?

As the issue is on the url https://docs.lizmap.com/current/en/ I was also wondering if there is a SSL/HTTPS configuration to check on **our** docs.lizmap.com server.

The exception you added looks good, no ? Thanks

**Comment by Gustry** [comment]
I will release a new version of the plugin now.
I will change the homepage URL, but as soon as this is fixed, I will put back this URL.

Thanks

**Comment by sumandari** [comment]
I'm not not sure about this, maybe @dimasciput have suggestion?
> As the issue is on the url https://docs.lizmap.com/current/en/ I was also wondering if there is a SSL/HTTPS configuration to check on our docs.lizmap.com server.

I will inform once it's deployed, thanks @Gustry
> I will release a new version of the plugin now.
I will change the homepage URL, but as soon as this is fixed, I will put back this URL.

**Comment by sumandari** [comment]
Hi @Gustry,  this fix has been deployed. Could you please give it a try and let me know if the issue exists. Thanks!

**Comment by Gustry** [comment]
Ok, I will release a new version soon I guess. Thanks !
