### ISSUE TITLE
Update documentation on /publish

### ISSUE THREAD

**Issue by sumandari** [qgis/QGIS-Django#171]
We need to update the documentation about forbidden folder in plugins zipfile

> Please see this thread https://lists.osgeo.org/pipermail/qgis-developer/2020-December/062720.html
> Maybe could it be better to use
> `for not_allowed_dir in ['__MACOSX/', '.git/', '__pycache__/']:`
> Moreover, I think those forbidden names should be specified in the plugin How to documentation at https://plugins.qgis.org/publish/
> 
> _Originally posted by @agiudiceandrea in https://github.com/qgis/QGIS-Django/pull/116#discussion_r537503257_

**Comment by timlinux** [comment]
Yes please add to the publishing page

**Comment by sumandari** [comment]
There's an error when go to update page in admin
![image](https://user-images.githubusercontent.com/40058076/111934597-b3ed5800-8afc-11eb-8b1f-e9c3faddf8ec.png)

```
NoReverseMatch at /admin/flatpages/flatpage/4/change/
Reverse for 'tinymce-js' not found. 'tinymce-js' is not a valid view function or pattern name.
```

**Comment by sumandari** [comment]
the error fixed with https://github.com/qgis/QGIS-Django/pull/172

**Comment by sumandari** [comment]
/publish/ updated:

![image](https://user-images.githubusercontent.com/40058076/111955700-cc716880-8b24-11eb-9a7f-30563c1c1f6c.png)

![image](https://user-images.githubusercontent.com/40058076/111956012-3b4ec180-8b25-11eb-8340-897db6335ea1.png)
