### ISSUE TITLE
Deploying from scratch with Rancher

### ISSUE THREAD

**Issue by ymoisan** [qgis/QGIS-Django#176]
Hi,

Can the set of containers in this project be deployed on a private cloud infrastructure using Rancher ?  I've seen Rancher can be used to update an existing installation, but can it be used to deploy a new setup from scratch ?  Our use case is that we'd like to have a local plugins repo for things that are of interest only to us or that we are not ready to open up to the community.  Thanx for this project.

**Comment by sumandari** [comment]
Hello @ymoisan,

Thank you for your interest in this project and the rancher deployment. The answer is yes, we can. We have been using rancher for production.

**Comment by ymoisan** [comment]
Hello @sumandari.  We are just having a hard time finding how to do that ;-).

**Comment by stlaurentc** [comment]
Hi @sumandari I'm also interested to know how to do that !

**Comment by elpaso** [comment]
@ymoisan if you need a simple plugin private repo you might want to have a look to: 
https://github.com/planetfederal/qgis-plugin-repos
https://github.com/planetfederal/qgis-plugins-xml

**Comment by sumandari** [comment]
Hi @ymoisan @stlaurentc, since the integration environment in Rancher was created by another maintainer, it will be some time to elaborate the rancher documentation. I will post here once it's ready.
Please have a look at repositories mentioned above (thank you @elpaso!) for another options.

**Comment by timlinux** [comment]
@sumandari also we should clarify if we are talking rancher 1.x here or rancher 2.x (k8 based). For me I think any work we do on making this publicly re-usable should probably be done on rancher 2.x since 1.x is going end-of-life.

**Comment by Xpirix** [comment]
Update: we have switched to a docker-compose-based for deployment. Please see https://github.com/qgis/QGIS-Django/blob/master/dockerize/README.md from more details.
