### ISSUE TITLE
Add gallery view mode for hub (styles, models, projects)

### ISSUE THREAD

**Issue by anitagraser** [qgis/QGIS-Django#185]
I think we could also add a gallery view @sumandari like Klas had in his origina mockup. 

_Originally posted by @timlinux in https://github.com/qgis/QGIS-Django/issues/123#issuecomment-740690847_

**Comment by sumandari** [comment]
Well noted @anitagraser. I will add the gallery view for hub.

**Comment by sumandari** [comment]
This feature has been deployed on prod. I will close this for now
