### ISSUE TITLE
Owners field of plugins should be searchable

### ISSUE THREAD

**Issue by simonseyock** [qgis/QGIS-Django#191]
The owners field in the plugin management is a tiny scrollable list of **all** users. This makes it very hard to find a specific user.
It would be way more usable if it was a searchable combo box.

**Comment by sumandari** [comment]
Hi @simonseyock, thank you for your input. 
I agree with you. The bigger selector will make it easier to see the text.
For now, we can search the value by type quickly inside the box.

![191](https://user-images.githubusercontent.com/40058076/132837574-5acc5b6b-d9a8-4b49-a7c5-53126739e9f9.gif)

**Comment by gacarrillor** [comment]
This should be already closed (by https://github.com/qgis/QGIS-Django/pull/290).
