### ISSUE TITLE
Changing owner of a plugin to a different LDAP user

### ISSUE THREAD

**Issue by robe2** [qgis/QGIS-Django#194]
On OSGeo LDAP I deleted a user erwirth.  This user had plugins registered under erwirth.  Is it possible for those plugins to be transferred to a different OSGeo account.  I'm not sure which new one was set up.

If not I presume if he recreates this account he should be all set, but then he'd have two and each one would have to have a separate email.

**Comment by sumandari** [comment]
Hi @robe2, 
yes, I think it's possible.
Would you please send the detail:  old username, new username, registered plugins and evidence that the old username and the new username is the same person to email: sumandari@kartoza.com cc: dimas@kartoza.com and tim@kartoza.com
We will check and verify based on the detail provided.
Thank you.

**Comment by poetyi** [comment]
> 
> 
> On OSGeo LDAP I deleted a user erwirth. This user had plugins registered under erwirth. Is it possible for those plugins to be transferred to a different OSGeo account. I'm not sure which new one was set up.
> 
> If not I presume if he recreates this account he should be all set, but then he'd have two and each one would have to have a separate email.

Thank you for the comment,
a little correction, my username is
_ewirth_ (instead erwirth)
at the site: https://plugins.qgis.org/accounts/login/

**Comment by robe2** [comment]
Sorry for the trouble.  Well at least I know it's possible in the future if someone asks.  I thought @poetyi  had created a new account after I deleted his old. Turns out he didn't so he recreated his old one and is all set now.
