### ISSUE TITLE
State of the stack used in the repository

### ISSUE THREAD

**Issue by Gustry** [qgis/QGIS-Django#225]
I'm just looking at versions when launching the stack on my local machine with docker : 

* Python 3.7
  * Still supported until June 2023
  * Upgrade to 3.9 ?
* Django 2.2.24
  * Supported until Apr 2022, coming soon
  * Latest LTS is 3.2.9
* PG 9.6
  * Not supported anymore since November 2021
  * Upgrade to 13 ?
* RabbitMq 3.6
  * Not supported since 31 May 2018 !
  * Upgrade to 3.9.11

The biggest step is I think Django.

I'm keeping notes here. We can check and upgrade.

If I'm not wrong, this stack is used as well in production with rancher ?

**Comment by Gustry** [comment]
Django 4.0 has been released recently, but the LTR version is not before beginning of 2023 with 4.2

**Comment by dimasciput** [comment]
@Gustry 

> If I'm not wrong, this stack is used as well in production with rancher ?

Yes that's correct.

> Django 4.0 has been released recently, but the LTR version is not before beginning of 2023 with 4.2

I think we should be fine with the django 3.2.9 until 4.2 is released.

**Comment by Gustry** [comment]
I started the upgrade to 3.2 in the PR https://github.com/qgis/QGIS-Django/pull/233
For Python, I have created a ticket in kartoza/django-base image

**Comment by Xpirix** [comment]
Thanks for this work. The stacks are now running with recent versions. Please see #374
