### ISSUE TITLE
We need an admin UI for managing versions

### ISSUE THREAD

**Issue by timlinux** [qgis/QGIS-Django#237]
Currently the QGIS versions list is maintained here

![imagem](https://user-images.githubusercontent.com/178003/151532547-a7bfc994-5da8-410e-a44f-3cc0ce0c7232.png)

https://github.com/qgis/QGIS-Django/blob/aa91b575f4920b78e74f176a306fbf4963c0c3ed/qgis-app/plugins/tasks/generate_plugins_xml.py#L21

Which is very fragile and manual, requiring a developer to update code and redeploy the site each time a new version of QGIS is released. Can we make an admin UI for doing this. It would still be manual but at least will not require code changes etc. to update.

**Comment by dimasciput** [comment]
We can update the versions here https://plugins.qgis.org/admin/preferences/sitepreference/2/change/

**Comment by agiudiceandrea** [comment]
@timlinux @dimasciput it seems 3.30 and 3.31 are missing.

**Comment by dimasciput** [comment]
Hi @agiudiceandrea , you can add the versions here https://plugins.qgis.org/admin/preferences/sitepreference/2/change/

I have added those two versions, it will take an hour to generate the plugins xml file.

**Comment by agiudiceandrea** [comment]
Thanks @dimasciput. I don't have admin right to access https://plugins.qgis.org/admin/preferences/sitepreference/2/change/
