### ISSUE TITLE
Add plugin/resource name to HTML title

### ISSUE THREAD

**Issue by nyalldawson** [qgis/QGIS-Django#242]
Currently, the HTML title of the plugins site is ALWAYS "QGIS Python Plugins Repository", regardless of which page on the site you are actually visiting. 

This is problematic for search engines, as the results when searching for a specific QGIS plugin by name seem to be directing just to a generic "QGIS plugins" page:

![image](https://user-images.githubusercontent.com/1829991/159187223-f28d261a-1476-44f8-8710-0a11a52cc006.png)

This would be remedied by adding a "— plugin name" suffix (or "plugin name — " prefix) to the HTML title when the page relates to a specific plugin or resource, e.g "Crayfish — QGIS Python Plugins Repository".

**Comment by dimasciput** [comment]
this is fixed now
<img width="931" alt="image" src="https://user-images.githubusercontent.com/1979569/160087766-5c5d58fc-9565-4146-b62c-89f29d1fc148.png">

**Comment by agiudiceandrea** [comment]
This issue report could be closed, since the issue it is fixed now.

**Comment by nyalldawson** [comment]
Great, thanks @dimasciput !
