### ISSUE TITLE
Sorting of plugins list doesn't work if filtered by a tag or a author

### ISSUE THREAD

**Issue by agiudiceandrea** [qgis/QGIS-Django#245]
From "All plugins" https://plugins.qgis.org/plugins/
- click on plugin tag "cad" -> https://plugins.qgis.org/plugins/tags/cad/
- click on any column header: the sorting order does not change

**Comment by dimasciput** [comment]
@agiudiceandrea please check again, this should be fixed now.

**Comment by agiudiceandrea** [comment]
Yes, it seems OK now. Thanks a lot!
