### ISSUE TITLE
http://plugins.qgis.org/plugins/

### ISSUE THREAD

**Issue by LeneFischer** [qgis/QGIS-Django#25]
At the plugin page http://plugins.qgis.org/plugins/ you can´t list a page with all plugins or choose alphabetic. Now you have to click next a lot of times to eg. go to page 21.

![xxx](https://cloud.githubusercontent.com/assets/9905437/16481680/c752519e-3eac-11e6-909e-542727bc2f12.JPG)
Whis a list like this and an "All in one- page":
![yyy](https://cloud.githubusercontent.com/assets/9905437/16481723/05aec044-3ead-11e6-8444-6fca753fb1a7.JPG)

Regards
Lene Fischer

**Comment by elpaso** [comment]
all in one page with 600+ plugins will result in a huge page, you can use the xml for that: http://plugins.qgis.org/plugins/plugins.xml

**Comment by LeneFischer** [comment]
Most of the descriptions are text and the images very small, so all-in -one will not be so heavy.
Being able to sort and search in all is a very nice feature.
If a button - show all - is added, you can choose. And if you find it too heavy, being able to have an alphabetic list again.

The XML page is good, but not sorted in alphabetic order. Perhaps a link to the "secret" xml ;-)

**Comment by elpaso** [comment]
The button "show all" was there, it was removed because it was too slow to load.

**Comment by timlinux** [comment]
@Xpirix maybe you could add a 'show more' button that loads more records into the current page? Any other ideas?

**Comment by Xpirix** [comment]
@timlinux Sure, I can also add a dropdown list to choose the number of records per page.
