### ISSUE TITLE
Plugin titles / tabs all look the same in browser tabs

### ISSUE THREAD

**Issue by DelazJ** [qgis/QGIS-Django#26]
Original report: https://github.com/qgis/QGIS-Website/issues/360

Let's open a few tabs about plugins in our browser.

The result is as you can see.

![275791f2-3deb-11e6-9e11-dcc1a4fe16b8](https://cloud.githubusercontent.com/assets/7983394/16495422/a31a00e2-3eed-11e6-82ce-a95fffe66c12.jpg)

They all have the same HTML TITLE..

What they should have is their or keyword prepended:
so that both type of pages
https://plugins.qgis.org/plugins/tags/ibama/
https://plugins.qgis.org/plugins/LocatePoints/
would all have the distinguishing parts of their names near the
beginning of the TITLE so we could tell them apart in browser tabs or
in a browser History list.

**Comment by kannes** [comment]
I did some stuff in https://github.com/kannes/QGIS-Django/tree/titles to allow titles have the important stuff in the beginning, eg. "Plugin Name | QGIS Python Plugin Repository".

It is **untested** and I am just guessing the syntax!

I could not figure out where to change the title of the tag pages like https://plugins.qgis.org/plugins/tags/area/ . There is no template defined for that? Should be like "Tag: tag | QGIS Python Plugin Repository" I think.
