### ISSUE TITLE
Plugin maintainer cannot be changed

### ISSUE THREAD

**Issue by koebi** [qgis/QGIS-Django#260]
Currently, the metadata doesn't specify any `maintainer`-field, even though the plugin details page (e.g. [for the ORStools plugin](https://plugins.qgis.org/plugins/ORStools/)) has this info.

It also has an author field that can be changed, even though it feels like it should be the other way around - where the original author is fixed (as that will not change) and the maintainer can be changed (since that does change from time to time, as has happened with the ORStools plugin).

I'd suggest making the maintainer-field editable, possibly controlled by the metadata.

**Comment by gacarrillor** [comment]
Solved in https://github.com/qgis/QGIS-Django/pull/316
@dimasciput @Xpirix, please close this issue.
