### ISSUE TITLE
Initial plugin view is on second tab but shows info of first tab

### ISSUE THREAD

**Issue by koebi** [qgis/QGIS-Django#261]
When clicking on a plugin, i.e. [this one](https://plugins.qgis.org/plugins/ale/), I get to the plugin site.

This usually has three "tabs": About, Details and Version.
Every now and then, the About tab will be missing.

The box under the tabs always shows the info from the first tab, while the tab highlighted makes it seem like I'm on the second tab:
![Screenshot 2022-09-15 at 15-39-08 Advanced Line Editor — QGIS Python Plugins Repository](https://user-images.githubusercontent.com/4692974/190418745-a7033a4f-70ef-40ac-a542-bdde444032bc.png)
(image taken from link above)

**Comment by agiudiceandrea** [comment]
"The box under the tabs always shows the info from the first tab, while the tab highlighted makes it seem like I'm on the second tab": confirmed.
"Every now and then, the About tab will be missing": I cannot confirm.

**Comment by dimasciput** [comment]
@koebi @agiudiceandrea this issue has been fixed.

**Comment by agiudiceandrea** [comment]
> this issue has been fixed.

Great! Thanks!

**Comment by agiudiceandrea** [comment]
@dimasciput, this issue report can be closed.
