### ISSUE TITLE
Due to the size of the search button, certain window widths will cause the header to overflow into a second row and cover up the main content:

### ISSUE THREAD

**Issue by jayenashar** [qgis/QGIS-Django#263]
Due to the size of the search button, certain window widths will cause the header to overflow into a second row and cover up the main content:

![image](https://user-images.githubusercontent.com/590385/192040611-b7e526e2-6e9e-4931-9a68-acd55306296a.png)

On a related note: in night mode, the menu icon is black on dark background: 

![image](https://user-images.githubusercontent.com/590385/192040640-3e250d5f-d3cb-4139-a732-907ccc995208.png)

_Originally posted by @anitagraser in https://github.com/qgis/QGIS-Django/issues/241#issuecomment-1256581633_

**Comment by dimasciput** [comment]
<img width="1482" alt="Screenshot 2023-07-18 at 2 04 13 PM" src="https://github.com/qgis/QGIS-Django/assets/1979569/28fa0884-73f6-4a7b-b675-f0330c55df3f">

I've changed the search text to a search icon; this shouldn't be an issue anymore.
