### ISSUE TITLE
Create API to Interact with Hub Resources

### ISSUE THREAD

**Issue by ismailsunni** [qgis/QGIS-Django#275]
Currently, we are only able to download/upload/update QGIS Hub Resource via the web. It would be really great if we have an API to do this. Then we can integrate the QGIS Hub into QGIS so that QGIS users are able to access it directly from QGIS.

### API needed:
~**for starter (read-only)**~
~- Get the list of resources for each resource type (e.g. style, project, model, etc)~
~- Get the information for each resource~
~- Download the resource itself~

**For later**
- Authentication
- Create/Upload a new resource for each resource type
- Edit existing resources for each resource type
- Delete resource for each resource type

cc @timlinux @dimasciput

**Comment by ismailsunni** [comment]
I found out that some of them are already there, see: https://github.com/qgis/QGIS-Django/blob/master/qgis-app/api/urls.py

**Comment by Xpirix** [comment]
@ismailsunni Please find the proposed changes at #471 

Regards.

**Comment by Xpirix** [comment]
Hi @ismailsunni , this has been deployed. Please let me know if you have any feedback.
