### ISSUE TITLE
Add an option to show plugins that are awaiting feedback 

### ISSUE THREAD

**Issue by NyakudyaA** [qgis/QGIS-Django#276]
# Problem

When reviewing plugins, we sometimes inform authors about issues through email or GitHub. There is no way to know which plugins are awaiting client feedback resolution. When you review plugins you will need to through the list again to check if the issues have been addressed.

# Solution

Add a new tab to show plugins waiting for feedback

![Screenshot from 2023-04-29 08-55-26](https://user-images.githubusercontent.com/2510900/235288572-02ffc99f-8647-4c47-a577-d3c855d82f1b.png)

To add the awaiting feedback option we can add it to the manage options for the plugin.

![image](https://user-images.githubusercontent.com/2510900/235288678-a123d112-946a-4a81-a639-d62fbcf9007c.png)

Additionally, it would also be nice to email the author through his email address to notify him that the plugin has been reviewed

**Comment by sumandari** [comment]
@NyakudyaA can you please elaborate if the platform has already had a review form for a plugin from a reviewer to the creators/owners? Or we need to create a form for giving them feedback and showing them link in the manage tab?

**Comment by NyakudyaA** [comment]
That hasn't been done yet, it would be lovely to have it
