### ISSUE TITLE
Resource API is missing Layer Definition File and 3D Model

### ISSUE THREAD

**Issue by ismailsunni** [qgis/QGIS-Django#280]
This API (https://plugins.qgis.org/api/v1/resources/ or https://github.com/qgis/QGIS-Django/blob/master/qgis-app/api/urls.py ) is supposed to return all the resources. But it only returns Style, Geopackage, and Model (missing layer definition file and 3D model)

**Comment by Xpirix** [comment]
Please find the proposed PR for this at #388
