### ISSUE TITLE
Disk space gradually filling up

### ISSUE THREAD

**Issue by timlinux** [qgis/QGIS-Django#282]
![image](https://github.com/qgis/QGIS-Django/assets/178003/87880c4f-3e1f-4a02-9dad-ee1384ed669f)

`````docker exec -ti 5e44428e3a92 bash  
find . -type f -name 'tmp*' | xargs rm  `´

![image](https://github.com/qgis/QGIS-Django/assets/178003/4a994799-980e-4654-b1d6-24eb4ec7e714)

![image](https://github.com/qgis/QGIS-Django/assets/178003/072fb069-c32c-4de5-8d7e-77300059dea8)

**Comment by Xpirix** [comment]
I think this should be fixed since we've migrated to a new server. We have 84% of free space now. I will monitor it continuously to see if it still filling up gradually.
