### ISSUE TITLE
Categories for the changelog are at the bottom

### ISSUE THREAD

**Issue by Gustry** [qgis/QGIS-Django#285]
I think the issue was there a long time ago and it has been fixed before.

On https://changelog.qgis.org/en/qgis/version/3.32/

Categories are only at the bottom of the list for now. It should be on the right side, always visible IMHO.

![image](https://github.com/qgis/QGIS-Django/assets/1609292/1792422e-9d74-4184-ab60-037a6a854b79)

**Comment by Xpirix** [comment]
Fixed with https://github.com/kartoza/prj.app/pull/1445
