### ISSUE TITLE
Select multiple owners in management page in huge owners select box

### ISSUE THREAD

**Issue by rduivenvoorde** [qgis/QGIS-Django#289]
Though related to #191 I think we have to come up with a way to handle the huge list of owners we have now...

See this mailing list thread: https://lists.osgeo.org/pipermail/qgis-developer/2023-June/065947.html

We have > 4000 owners now, and it is pretty hard to set multiple owners. The tip from #191 only works if you have 1 owner

Not sure how to implement this easily though...

@nyalldawson proposed to use a javascript hack to set multiple owners

```
owners_input = document.getElementById('id_owners')
const users = ["some_user", "another_user", "another_person"];
for (var i = 0; i < owners_input.options.length; i++) {
    if ( users.includes(owners_input.options[i].text))
    {
      console.log(owners_input.options[i].text);
      owners_input.options[i].selected = true;
    }
    else
    {
      owners_input.options[i].selected = false;
    }
}
```

**Comment by dimasciput** [comment]
@rduivenvoorde What if I make the selection like this?
[Screen Recording 2023-06-29 at 5.38.51 PM.webm](https://github.com/qgis/QGIS-Django/assets/1979569/4320e375-28fc-446f-afd8-c834c07c8cc3)

**Comment by rduivenvoorde** [comment]
@dimasciput SUPER!!!! Thanks! Sorry for this late message...

**Comment by nyalldawson** [comment]
@dimasciput that looks BRILLIANT! Thank you!

**Comment by dimasciput** [comment]
@rduivenvoorde The fix has been deployed to the site.

**Comment by gacarrillor** [comment]
Can somebody with proper rights close this and https://github.com/qgis/QGIS-Django/issues/191?

**Comment by gacarrillor** [comment]
Thanks @Xpirix.

**Comment by Xpirix** [comment]
@gacarrillor You're welcome.
