### ISSUE TITLE
Link directly to "versions" tab

### ISSUE THREAD

**Issue by m-kuhn** [qgis/QGIS-Django#313]
I sometimes ask users to download older versions of a plugin. For example if someone reports something as a regression, they can continue to work with an older version until a fix is implemented.

Currently, when linking to a plugin page, we always end up at "About", it would be great if we could directly link to "Versions", e.g. something like https://plugins.qgis.org/plugins/qfieldsync#versions

**Comment by Gustry** [comment]
+1 for me too, having an anchor to the versions tab would be nice indeed.

**Comment by Xpirix** [comment]
Hello everyone,

Please find a PR for this feature at: https://github.com/qgis/QGIS-Django/pull/317.

Best regards.
