### ISSUE TITLE
Add an option "Create a bugtracker"

### ISSUE THREAD

**Issue by akbargumbira** [qgis/QGIS-Django#32]
[This issue has been migrated from the old QGIS issue tracker.](https://hub.qgis.org/issues/23)
## Author

[Paolo Cavallini](https://hub.qgis.org/users/10) (@pcav) 
## Description

On uploading a plugin, the author should be presented with the option of automatically create a bugtracker instance for it. This could be compulsory, or at least strongly recommended.
## Comments

 Paolo Cavallini (@pcav) :

> Pull Request or Patch supplied set to No
> 
> This is now compulsory, but not automatic.

 Paolo Cavallini (@pcav) :

> Priority changed from High to Low

**Comment by kannes** [comment]
Considering that online-hosted code repositories are commonplace nowadays and Github, Gitlab, Bitbucket etc all have issues integrated, I think this can be closed as request from the past. :)
