### ISSUE TITLE
Missing some plugins icons in the plugins lists and pages

### ISSUE THREAD

**Issue by agiudiceandrea** [qgis/QGIS-Django#337]
In the plugins lists, some plugins icons are not displayed.

See:

https://plugins.qgis.org/plugins/latest/

![image](https://github.com/qgis/QGIS-Django/assets/16253859/b48d157f-8e31-4617-afae-14ac1c5db837)

https://plugins.qgis.org/plugins/most_rated/

![image](https://github.com/qgis/QGIS-Django/assets/16253859/4a3c590c-6875-4666-af12-777911f62605)

**Comment by agiudiceandrea** [comment]
It looks like plugin icon is also missing in some plugin page e.g.:

https://plugins.qgis.org/plugins/geo2local-master/
![image](https://github.com/qgis/QGIS-Django/assets/16253859/baf68dc3-23f1-49e8-9cc1-615413596ffc)


https://plugins.qgis.org/plugins/space_time_cube/
![image](https://github.com/qgis/QGIS-Django/assets/16253859/633eceb6-ffd8-4eec-97c8-eace0ae619d2)

**Comment by Xpirix** [comment]
Dear @agiudiceandrea 

The issue has been fixed. Clearing cached images on the browser might be needed to see the changes. PR #340, once implemented, should prevent similar issues from happening.

Best regards,
![image](https://github.com/qgis/QGIS-Django/assets/43842786/61dba2a2-2b9d-4103-b7a7-b8029433ce06)

**Comment by agiudiceandrea** [comment]
Thanks! Issue fixed.

**Comment by Xpirix** [comment]
You're welcome.
