### ISSUE TITLE
user image is missing from planet pages

### ISSUE THREAD

**Issue by akbargumbira** [qgis/QGIS-Django#34]
[This issue has been migrated from the old QGIS issue tracker.](https://hub.qgis.org/issues/4508)
## Author

[Alessandro Pasotti](https://hub.qgis.org/users/15) (@elpaso)
## Description

See top right in page:
http://users.qgis.org/planet/tag/thematics/
the missing image is:
http://users.qgis.org/static//feedjack/default/img/faces/woostuff.png
which leads to 404
I'm not sure if it's just a matter of hiding the IMG tag (template stuff) if the image is missing or if this is a bug somewhere in feedjack.
## Comments

Paolo Cavallini (@pcav) :

> Assigned to set to Tim Sutton (@timlinux)

**Comment by kannes** [comment]
Can't reproduce this (anymore).

**Comment by timlinux** [comment]
@Xpirix see if you can reproduce and close if not

**Comment by Xpirix** [comment]
@timlinux I can't reproduce this too. I will close it then.
