### ISSUE TITLE
can't delete a falsly uploaded plugin revision, might be due to wrong version number

### ISSUE THREAD

**Issue by jannefleischer** [qgis/QGIS-Django#341]
Sadly, I am unable to edit or delete a plugin revision in the repository. I uploaded a version with the wrong version number and want to get rid of it, though I can't because the delete-button (and the edit-buttons) brings only a 404 error.

https://plugins.qgis.org/plugins/os_walk_eu_plugin/#plugin-versions
The version 2.rc2 should be deleted, the most current version is 1.99.1

![image](https://github.com/qgis/QGIS-Django/assets/12968103/a8d93e1f-04df-426e-ba82-60b2f21adb71)

**Comment by jannefleischer** [comment]
I think this hits: https://github.com/qgis/QGIS-Django/blob/master/qgis-app/plugins/views.py#L1059-L1060 - don't know why, though. Django-internals...?

**Comment by Xpirix** [comment]
Dear @jannefleischer 

This issue has been fixed. You can interact with this version now.
The issue seems specific to this version. Indeed, the version exists in the DB but it needed to be saved manually from the admin page. I'm also not sure why. 

Best regards,
