### ISSUE TITLE
Planet not updated

### ISSUE THREAD

**Issue by akbargumbira** [qgis/QGIS-Django#35]
[This issue has been migrated from the old QGIS issue tracker.](https://hub.qgis.org/issues/4879)
## Author

[Alexander Bruy](https://hub.qgis.org/users/173) (@alexbruy)
## Description

RSS at http://plugins.qgis.org/planet/ is not updated anymore, while at http://qgis.org/planet it works. Seems one of this should be removed.
## Comments

Anita Graser (@anitagraser) :

> Status changed from Open to Closed
> 
> I think that's fine now.   

Anita Graser (@anitagraser) :

> Status changed from Closed to Reopened
> Priority changed from Low to Normal
> 
> Sorry, closed too fast ...

Paolo Cavallini (@pcav) :

> Still valid?

Akbar Gumbira (@akbargumbira) :

> I think both of them pointing to the same thing

**Comment by kannes** [comment]
There is no RSS feed provided by Planet, so I guess Alex meant the Planet itself.

Anyways, as of right now, the last aggregated post is from last week so it works fine.

This issue can be closed.
