### ISSUE TITLE
Repository url does not get updated when uploading a new version of the plugin

### ISSUE THREAD

**Issue by raymondnijssen** [qgis/QGIS-Django#350]
After changing the links to homepage, tracker and repository, the repository link does not get updated in the plugin metadata as displayed in the QGIS plugin manager.

The problem could be in this line, not containing "repository":

https://github.com/qgis/QGIS-Django/blob/6d03c8428abe9df7634bbf810bbcb63709b11d45/qgis-app/plugins/views.py#L908

**Comment by Xpirix** [comment]
Dear @raymondnijssen , thanks for your help. That line is indeed what caused the issue.

I've created a new PR for this at #351.

Regards.
