### ISSUE TITLE
Plugin list doesn't include timezone for create/update dates

### ISSUE THREAD

**Issue by pathmapper** [qgis/QGIS-Django#353]
Therefore it's not possible to show the correct time in QGIS plugin manager which is for `<update_date>`:

`2024-02-02T06:57:07.532998+00:00`

https://plugins.qgis.org/plugins/plugins.xml?qgis=3.32

![grafik](https://github.com/qgis/QGIS-Django/assets/20856381/ab2d2279-1503-473d-8a4f-a39e1aeb862f)

![grafik](https://github.com/qgis/QGIS-Django/assets/20856381/34537ad9-f1e9-4b7e-9157-b13c23861a33)

**Comment by Xpirix** [comment]
Dear @pathmapper 

Please find the proposed fix for this issue at #360 

Regards

**Comment by Xpirix** [comment]
The changes fixing this issue have been deployed, and I'm closing it.
