### ISSUE TITLE
Main plugin page does not partially display stars for votes

### ISSUE THREAD

**Issue by pathmapper** [qgis/QGIS-Django#354]
so it looks like there are different ratings displayed.

e.g. https://plugins.qgis.org/plugins/shapetools/

![grafik](https://github.com/qgis/QGIS-Django/assets/20856381/008f0b6f-2bfe-482b-aad3-fe822ba729af)

which has an average vote of 4.64 according to

https://plugins.qgis.org/plugins/plugins.xml?qgis=3.32

![grafik](https://github.com/qgis/QGIS-Django/assets/20856381/19409ed7-1088-4172-9423-e080d1c95e65)

---

https://plugins.qgis.org/plugins/popular/ and QGIS plugin manager are showing this as expected.

![grafik](https://github.com/qgis/QGIS-Django/assets/20856381/733353e5-1278-42a5-9434-b9a71e42e294)

![grafik](https://github.com/qgis/QGIS-Django/assets/20856381/afd77523-c384-47df-8d1a-82a293312bbf)

**Comment by Xpirix** [comment]
Dear @pathmapper 

Please find the proposed PR for this issue at #359 

Regards

**Comment by Xpirix** [comment]
The changes have been deployed. I'm closing this one.
