### ISSUE TITLE
Plugin does not show up in sites or plugin.xml while it is uploaded and visible in Django admin pages

### ISSUE THREAD

**Issue by rduivenvoorde** [qgis/QGIS-Django#364]
Hi,

I'm contacted by the author of the "NVDB beta" plugin.
That the plugin seems never approved. But I cannot find it (to approve) either, so I think it is not seen by the 'approvers'.

He uploaded the plugin, (with to me strange name 'beta').
And because it did not show up in plugins made the zip also available via:
https://github.com/JACCCostring/QGISPluginNVDBv1.0/tree/master
Note the repo is:
https://github.com/JACCCostring/NVDBPlugin

If I log in in and search for NVDB I cannot find it:
https://plugins.qgis.org/search/?q=NVDB

Because it is not approvied it's not visible in plugins.xml

https://plugins.qgis.org/plugins/plugins.xml?qgis=3.30

But logged in in Django interface I CAN find the user and the plugin (screenies):

![Screenshot from 2024-02-23 09-01-38](https://github.com/qgis/QGIS-Django/assets/731673/0ca57ad4-131d-4d68-b9f9-cdeaa338dc27)

![Screenshot from 2024-02-23 08-59-39](https://github.com/qgis/QGIS-Django/assets/731673/9b05c2c9-20c6-4862-9a4b-73d63a24c5ec)

Is this possible? 
Is it an issue in the metadata.txt?
I agree that putting 'beta' in the name, and using the default plugin icon, and coloring used make look it a little 'beta', but still.

![Screenshot from 2024-02-23 09-09-35](https://github.com/qgis/QGIS-Django/assets/731673/8ad5d166-a0ce-4f94-a25a-c964f5dcc1d9)

**Comment by Xpirix** [comment]
Dear @rduivenvoorde , 

You're right, we cannot find unapproved plugins in plugins.xml but also in the search results. However, they can be found in the Unapproved list if you're logged in as a staff user. The plugin `NVDB beta` for example is listed on the second page of that list (screenshot below).

Best regards

![image](https://github.com/qgis/QGIS-Django/assets/43842786/7f067e7e-475f-405b-a2d2-b9e69fe0e0ec)

**Comment by rduivenvoorde** [comment]
Ah, thanks. Yes I can see it myself now.

I'll then ask the owner to ask for a review (and or remove the 'beta' label)

Closing this one
