### ISSUE TITLE
Plugins page navigation menu error on mobile view 

### ISSUE THREAD

**Issue by ioalexei** [qgis/QGIS-Django#369]
## Description

When viewing the mobile version of plugins.qgis.org, tapping the hamburger menu only shows the site navigation momentarily before disappearing. 

It should stay open so that the links can be clicked/tapped for mobile users. 

(Using Firefox on Android 14) 

Page URL:
plugins.qgis.org

**Comment by rduivenvoorde** [comment]
> someone with appropriate rights transfer it there
@DelazJ thanks for the hint, did not know this was this easy to do!

**Comment by Xpirix** [comment]
Hello everyone,

Please find the proposed PR for this issue at #385
