### ISSUE TITLE
Add user comments

### ISSUE THREAD

**Issue by akbargumbira** [qgis/QGIS-Django#37]
[This issue has been migrated from the old QGIS issue tracker.](https://hub.qgis.org/issues/6478)
## Author

[Paolo Cavallini](https://hub.qgis.org/users/10) (@pcav)
## Description

As above
## Comments

Paolo Cavallini (@pcav) :

> Assigned to set to Alessandro Pasotti (@elpaso)

Alessandro Pasotti (@elpaso) :

> Assigned to deleted (Alessandro Pasotti)

Paolo Cavallini (@pcav) :

> It would be good to let user add comments both from the web and from the QGIS interface

Akbar Gumbira (@akbargumbira)

> Paolo: can you explain more for this?

Paolo Cavallini (@pcav) :

> It would be nice to go more social, allowing not only votes from the users (both from the web interface and from QGIS itself), but also comments, that could help others to understand plugin usefulness, quality, etc.
> This should probably be allowed for registered users only, so it would require a bit of thought.

**Comment by timlinux** [comment]
I dont like this idea. Then we need to moderate comments and we dont have the bandwidth to deal with spammers etc.
