### ISSUE TITLE
Feature request: show number of results returned in search

### ISSUE THREAD

**Issue by ioalexei** [qgis/QGIS-Django#371]
There is no indication of how many results are returned by a query. 

This is fine for searches that only return a single page of results, but is confusing for larger searchers (e.g. "land") that return several pages of results. 

It would be helpful to have: 
1. An indication of the total search results returned (e.g. After the **Search Results** header - so it would show **Search results (X items found)**
*edit: even better would be "Search results for "search term": X items found"*

2. For searches that return a large number of results over several pages, an indication of how many pages of results and what the current page is
(at the moment it only shows links for previous page and next page)

**Comment by Xpirix** [comment]
Dear @ioalexei , please find the proposed fix for this issue at #383

**Comment by ioalexei** [comment]
Looks great to me, thanks for working on it @Xpirix !

**Comment by Xpirix** [comment]
My pleasure.
