### ISSUE TITLE
Search results include "None" entries

### ISSUE THREAD

**Issue by ioalexei** [qgis/QGIS-Django#372]
Searching for Kartoza in the plugin search returns several plugin results but also two entries for "None" which just link back to the search query. 

https://plugins.qgis.org/search/?q=kartoza

![image](https://github.com/qgis/QGIS-Django/assets/3179403/8a03a733-c377-4002-8bf9-59e1f4ff52d9)

**Comment by Xpirix** [comment]
Dear @ioalexei ,

I've fixed it for now. I think that the search index doesn't rebuild automatically when a plugin is deleted. A similar issue has been also reported in the past (https://github.com/qgis/QGIS-Django/issues/24). I will spend more time to understand how it works and try to prevent it.

Regards.
