### ISSUE TITLE
Plugin licence

### ISSUE THREAD

**Issue by akbargumbira** [qgis/QGIS-Django#38]
[This issue has been migrated from the old QGIS issue tracker.](https://hub.qgis.org/issues/6617)
## Author

[Paolo Cavallini](https://hub.qgis.org/users/10) (@pcav)
## Description

In most plugins there is no separate licence file, and in many there is no licence whatsoever.
I think this should be a requirement for accepting a plugin on the repo, and should ask authors to fix this.
IMHO we should establish a standard way to add it (e.g. provide a LICENSE file and put license header to all sources, probably integrating in Plugin Builder).

Unsure whether this is the right place to place this ticket - feel free to move it elsewhere.

**Comment by Guts** [comment]
Hello there,

While trying to publish or update a plugin, we discover a little surprised the error message related to the deployment of [this PR](https://github.com/qgis/QGIS-Django/pull/309) :

> Fault string: <Fault 1: 'File upload must be a valid QGIS Python plugin compressed archive. Cannot find LICENSE in plugin package.'>

See upstream on qgis-plugin-ci project (I'm one of the maintener): https://github.com/opengisch/qgis-plugin-ci/issues/255

I think that this kind of change, which breaks the plugins'publication flow, should be discussed before to be implemented (an issue from 1 person seems to be insufficient), announced to the community, a warning campaign should be run and a transitional phase should be implemented (warning for 6 months, then error). This has a direct impact on hundreds (thousands?) of plugin developers on a community project with several million end users.

I suggest reverting and starting a communication and preventive work upstream:

- update documentation: https://docs.qgis.org/3.28/en/docs/pyqgis_developer_cookbook/plugins/plugins.html
- communicate on the QGIS Dev list
- integrate a warning mechanism
- manage the QGIS versions concerned (only applicable to new QGIS released versions after this being merged)

**Comment by Guts** [comment]
Trying to get some discussion and seing that another PR has been merged and deployed without a word, I've moved this topic on QGIS Dev mailing list: https://lists.osgeo.org/pipermail/qgis-developer/2023-November/066252.html
