### ISSUE TITLE
The new version of my plugin does not appear 

### ISSUE THREAD

**Issue by florentfgrs** [qgis/QGIS-Django#382]
Hi, 

This morning I released a new version of my plugin (version `0.6.2`). As can be seen on this screenshot from plugins.qgis.org

![image](https://github.com/qgis/QGIS-Django/assets/36446612/4153037b-c25f-4625-9c35-59bca0df9c72)

More than 6 hours later, this version still hasn't appeared. Is there a problem? 

![image](https://github.com/qgis/QGIS-Django/assets/36446612/cc35defa-d4d2-40e4-88bb-3a9f0175f834)

**Comment by Xpirix** [comment]
Dear @florentfgrs 

You're right, it does not appear in the XML list. I will investigate further and gather more information about it.

Best regards

**Comment by Xpirix** [comment]
We noticed that the service to generate the XML didn't run correctly. It's fixed now, thanks to @dimasciput. The new plugin version should be listed in the XML now.

![image](https://github.com/qgis/QGIS-Django/assets/43842786/11632f6b-1a9a-4ad7-a1b5-efcc8b3b14be)

**Comment by florentfgrs** [comment]
Yes, that's it, thank you for your help. :smile:
