### ISSUE TITLE
Add an aggregate stats to the plugin manager's view

### ISSUE THREAD

**Issue by akbargumbira** [qgis/QGIS-Django#39]
[This issue has been migrated from the old QGIS issue tracker.](https://hub.qgis.org/issues/6808)
## Author

[Matteo Gismondi](https://hub.qgis.org/users/860) 
## Description

Add an aggregate stats to the plugin manager's view that shows number of downloads per country per month. For companies like mine to have such tool is indispensable to understand which country to target for marketing and business development.
Therefore this feature would be greately appreciated.
Thank you
Regards,
Matteo
## Comments

Akbar Gumbira (@akbargumbira)

> If I look at the database, there is no fields to correlate between the plugin, and the number of download per country. This is good though, we can show a heatmap of the number of downloads for all countries.

**Comment by timlinux** [comment]
@Xpirix let's start by you describing a design / approach here first before you start coding. Once we have reviewed, you can code it oK?

**Comment by Xpirix** [comment]
@timlinux , Please find below a description of the design/approach for this ticket.

1. **Create a `PluginDownloadByCountry` Model:**
    - [ ] Define a Django model named `PluginDownloadByCountry` with the following fields: `plugin_id`, `country_code`, `country_name`, `city`, `coordinates`, `downloaded_at`.

2. **Implement GeoIP2 Integration:**
    - [ ] Integrate GeoIP2 into the application.

3. **Handle Download Requests:**
    - [ ] When a download request is received:
        - [ ] Retrieve the country of the request from the IP address.
        - [ ] Instantiate a `PluginDownloadByCountry` instance with relevant details.

4. **Create GeoJSON Template:**
    - [ ] Integrate a GeoJSON template that includes information about all countries (boundary, code, name).

5. **Aggregate Stats in Plugin Manager's View:**
    - [ ] Create a new Django view that accepts parameters for month and year. If not set, use the current month, year.
    - [ ] Filter `PluginDownloadByCountry` based on the provided parameters and the current plugin.
    - [ ] Execute a query to group entries by `country_code` and include a `download_count` field.
    - [ ] Use the GeoJSON template to generate a GeoJSON with the `download_count` field.

6. **Enhance Plugin Page with Stats Tab:**
    - [ ] Add a new tab named `Stats` to the plugin page.
    - [ ] Display a graduated map using the `download_count` from the GeoJSON.
    - [ ] Include a list of the top 10 countries based on `download_count`.
    - [ ] Enable hovering over the map to display the download count for each country.

7. **Add Form for Specific Month and Year:**
    - [ ] On the `Stats` tab, include a form with fields for month and year to query statistics for a specific period.

According to these, I think this ticket will be split into smaller tickets.

**Comment by Xpirix** [comment]
Thank you @timlinux . Using Metabase makes it much easier. Please find the proposed PR at https://github.com/qgis/QGIS-Django/pull/331

**Comment by Xpirix** [comment]
This feature has been implemented.
