### ISSUE TITLE
RPC2 endpoint doesn't work

### ISSUE THREAD

**Issue by Xpirix** [qgis/QGIS-Django#397]
From @3nids , original comment at https://github.com/qgis/QGIS-Django/pull/374#issuecomment-2096337527

> It looks like pushing via qgis-plugin-ci doesn't work anymore
https://github.com/opengisch/qgis-pg-service-parser-plugin/actions/runs/8971769712/job/24638230525#step:11:23

> Do we need to adapt something so that the RPC2 endpoint works?
https://github.com/opengisch/qgis-plugin-ci/blob/67ac1ab3d6376ec0e05abee5ed1a25c1f7cb8ae0/qgispluginci/release.py#L443

> Thanks a lot!

**Comment by 3nids** [comment]
Thanks a lot for the quick heads up.

I'm still getting an error though: https://github.com/opengisch/qgis-pg-service-parser-plugin/actions/runs/8971769712/job/24670083383#step:11:24

**Comment by Xpirix** [comment]
The change has just been deployed. Could you please retry now?

**Comment by 3nids** [comment]
A bit further: https://github.com/opengisch/qgis-pg-service-parser-plugin/actions/runs/8971769712/job/24672468613#step:11:24

Now 403 forbidden.
Something changed regarding the authentication?

**Comment by Xpirix** [comment]
I think it's related to LDAP from OSGeo. We are now requesting to whitelist the new server for LDAP login to the new server.

We apologise for that. We will let you know as soon as we have access.

**Comment by jef-n** [comment]
access to ldap should work now. https://trac.osgeo.org/osgeo/ticket/3177#comment:2

**Comment by 3nids** [comment]
thanks for the reactivity!

now another error:

https://github.com/opengisch/qgis-pg-service-parser-plugin/actions/runs/8971769712/job/24683799982#step:11:24

```
HTTP/HTTPS headers: {'Date': 'Tue, 07 May 2024 14:06:40 GMT', 'Content-Type': 'text/plain; charset=UTF-8', 'Content-Length': '15', 'Connection': 'keep-alive', 'Report-To': '{"endpoints":[{"url":"https:\\/\\/a.nel.cloudflare.com\\/report\\/v4?s=C6dSykdilrn75pcUB%2B7lmFgaXrF3auT7pZZE3yjiqthFI6%2FbgUomACi7pHQzEfM%2FHlZIZU2pBPXy%2FzRbZ7kDrijRzLDh6dASDYEicxPaEdTqFuFiOgCIMSooWfGPzU3rR7SK"}],"group":"cf-nel","max_age":604800}', 'NEL': '{"success_fraction":0,"report_to":"cf-nel","max_age":604800}', 'X-Frame-Options': 'SAMEORIGIN', 'Referrer-Policy': 'same-origin', 'Cache-Control': 'private, max-age=0, no-store, no-cache, must-revalidate, post-check=0, pre-check=0', 'Expires': 'Thu, 01 Jan 1970 00:00:01 GMT', 'Server': 'cloudflare', 'CF-RAY': '8801c45c5e5d4b87-IAD', 'alt-svc': 'h3=":443"; ma=86400'}
Error code: 502
Error message: Bad Gateway
```

**Comment by mach0** [comment]
I guess thats the reason why a user on the mailing list complained about not being able to login the plugin page
(https://lists.osgeo.org/pipermail/qgis-community-team/2024-May/006137.html).
BTW: confirmed for me too .. -> Error: Bad gateway

**Comment by pathmapper** [comment]
Thanks! Confirmed that the login works for https://plugins.qgis.org/accounts/login/.

**Comment by 3nids** [comment]
fixed for us, thanks!
