### ISSUE TITLE
Only four stars are shown on the plugin list page

### ISSUE THREAD

**Issue by akbargumbira** [qgis/QGIS-Django#40]
[This issue has been migrated from the old QGIS issue tracker.](https://hub.qgis.org/issues/8645)
## Author

[Anita Graser](https://hub.qgis.org/users/17) (@anitagraser)
## Description

Plugins can be rated with up to five stars and on the individual plugin page, up to five stars are displayed. In the plugin list on the other hand, only a maximum of four stars is visible.
## Comments

Alessandro Pasotti (@elpaso) :

> It is because there are no plugins with score = 5.0000... (I don't remember how many significamt digits in a float)
> 
> But you're right, the algorithm could be better.

Anita Graser (@anitagraser)

> Can you change it to display five stars if the score is >= 4.5?

Alessandro Pasotti (@elpaso) :

> Probably yes, but I don't have time to do it now, sorry.
> 
> Also, the new plugin website I've developed during the HF has lot small fixes and the same look & feel of the new QGIS main website, unfortunately we didn't have enough time to push it online.
> 
> Every bug fix will have to wait until someone will find time to upgrade the wirtualenv on the server and push the new plugin site online.
> 
> If somebody wants to fix the rating issue, please look here:
> https://github.com/qgis/QGIS-Django/blob/master/qgis-app/plugins/templates/plugins/plugin_list.html#L98
> and here:
> https://github.com/qgis/QGIS-Django/blob/master/qgis-app/plugins/models.py#L26

Akbar Gumbira (@akbargumbira)

> See here the PR for this issue: https://github.com/qgis/QGIS-Django/pull/16

**Comment by kannes** [comment]
https://github.com/qgis/QGIS-Django/pull/16 had been merged. This can be closed.
