### ISSUE TITLE
Various recent issue reports about plugin install

### ISSUE THREAD

**Issue by agiudiceandrea** [qgis/QGIS-Django#401]
See:
- https://github.com/qgis/QGIS/issues/57352
- https://github.com/qgis/QGIS/issues/57383
- https://github.com/qgis/QGIS-Website/issues/1244

**Comment by Xpirix** [comment]
They should work without issue now. I've tested it against Windows (QGIS 3.28) and MacOS (QGIS 3.34). Please let me know if the issue still occurs.

**Comment by martinkean** [comment]
@Xpirix the Plugins repo is still down, bad gateway.

**Comment by Xpirix** [comment]
Hi @martinkean, it should be back now. We are currently working on a permanent fix for it.

**Comment by agiudiceandrea** [comment]
@martinkean please see https://lists.osgeo.org/pipermail/qgis-user/2024-May/054439.html.

**Comment by martinkean** [comment]
Kia ora Lova, yes that's working now, thanks!

All the best,
Martin
