### ISSUE TITLE
Error 500: internal application error When Requesting API with limit parameter.

### ISSUE THREAD

**Issue by ismailsunni** [qgis/QGIS-Django#407]
This API call is no longer working:
https://plugins.qgis.org/api/v1/resources/?limit=1000

![image](https://github.com/qgis/QGIS-Django/assets/1421861/104728ca-79a3-4c49-9a33-742bcdc0d687)

When you remove the limit or set the limit to 10 (max is 39), it works.

Unfortunately, it breaks the QGIS Hub Plugin.

Was this change planned/intentional or not?

Thanks!

**Comment by Xpirix** [comment]
Hi @ismailsunni, I've fixed it.

The error occurred on a specific style (40th) with an invalid thumbnail. So the request was not able to show other results.

**Comment by ismailsunni** [comment]
Thanks, it's working as before now.
