### ISSUE TITLE
Updating a plugin was banned because of license request

### ISSUE THREAD

**Issue by Newton787** [qgis/QGIS-Django#422]
I created a new version of my plugin and when I upload it I get this error:
"Errors occurred reading the plugin package (also check your plugin's metadata).
Cannot find LICENSE in plugin package. This file is required, consider adding it to the plugin package."

But the problem is that I added a License.txt file in the root directory of the plugin with GNU Free Documentation License v1.3 and in the metadata I mentioned with the parameter License=GNU1.3

![image](https://github.com/qgis/QGIS-Django/assets/20671069/92c3d44b-f83a-4f16-af6b-253c0ea83af3)

Am I forgetting to do something?

The license text is like this:

Copyright © 2024 NEWTON COELHO MONTEIRO.
Permission is granted to copy, distribute and/or modify this document
under the terms of the GNU Free Documentation License, Version 1.3
or any later version published by the Free Software Foundation;
with no Invariant Sections, no Front-Cover Texts, and no Back-Cover Texts.
A copy of the license is included in the section entitled "GNU
Free Documentation License".

**Comment by Xpirix** [comment]
Hi @Newton787 , I think it should work with `LICENSE` as a filename, in uppercase, without extension (.txt).

**Comment by Newton787** [comment]
I try it and no work too ~~

**Comment by Newton787** [comment]
Its works ^^ thanks

**Comment by Newton787** [comment]
For save without extension on Notepad go to save as, in file format select all files and the name file type "LICENSE" with double quotes

**Comment by Newton787** [comment]
How long should I normally wait to approve a new version of a plugin?

**Comment by Xpirix** [comment]
Sorry, I'm not sure about the delay.

@NyakudyaA, could you please help us here?

**Comment by NyakudyaA** [comment]
what was the name of the plugin ?

**Comment by Newton787** [comment]
POLO

**Comment by Newton787** [comment]
@NyakudyaA the name of plugin is Polo, this plugin is a tool for fire monitoring in Amazonas state of Brasil using firms and BdQueimadas data
