### ISSUE TITLE
Add a filter for "New" plugins to plugins website

### ISSUE THREAD

**Issue by akbargumbira** [qgis/QGIS-Django#44]
[This issue has been migrated from the old QGIS issue tracker.](https://hub.qgis.org/issues/10302)
## Author

[Borys Jurgiel](https://hub.qgis.org/users/89) (@borysiasty)
## Description

I would like to be able to sort or filter the plugins website, so that only new plugins would be shown, similar to the links for Featured, All, Stable, etc. in the op left corner.

Ticket moved from #9938
Original author of the ticket: http://hub.qgis.org/users/1219
## Comments

Akbar Gumbira (@akbargumbira)

> Hi Borys, can you explain more about the criteria of 'new' itself? Thanks

Borys Jurgiel (@borysiasty)

> Unfortunately I can't, as I only moved this ticket to more appropriate category. I just asked the author in the original ticket.

Ed B

> New = Any plugin uploaded or submitted to website in the last 30 days and it doesn't have to be 30 it could be any number of days. It could possibly include or exclude any new versions of a plugin.

**Comment by Xpirix** [comment]
@timlinux I see that the links for New Plugins and Updated Plugins are listed here. I think we can close this issue.

![Image](https://github.com/qgis/QGIS-Django/assets/43842786/2b429240-5b62-447b-add4-b45f16de4ab1)

**Comment by borysiasty** [comment]
Right, seems it's not valid anymore. Thanx!

**Comment by borysiasty** [comment]
So please close it, as I can't.
