### ISSUE TITLE
The QGIS plugins web portal home page contains an incorrect name and link to the PyQGIS cookbook

### ISSUE THREAD

**Issue by agiudiceandrea** [qgis/QGIS-Django#456]
### URL

https://plugins.qgis.org/

### Summary

The QGIS plugins web portal home page at https://plugins.qgis.org/ contains an incorrect name and link to the PyQGIS cookbook:

> Resources for plugin authors
> The [pyQGIS cookbook https://www.qgis.org/pyqgis-cookbook/plugins/index.html#developing-python-plugins contains a section on developing plugins and is an ongoing effort to collect tips and tricks about QGIS python programming generaly.

The name should be "PyQGIS cookbook" or "PyQGIS Developer Cookbook" and the link should be https://docs.qgis.org/3.34/en/docs/pyqgis_developer_cookbook/.

**Comment by jef-n** [comment]
probably bettre https://docs.qgis.org/latest/en/docs/pyqgis_developer_cookbook/

**Comment by Xpirix** [comment]
Hi @agiudiceandrea and @jef-n , It has been replaced with PyQGIS Developer Cookbook and points to https://docs.qgis.org/latest/en/docs/pyqgis_developer_cookbook/.

Thanks.
