### ISSUE TITLE
Quick OSM not working

### ISSUE THREAD

**Issue by arzoo3** [qgis/QGIS-Django#457]
my quick OSM is not working. It is showing error again and again. Please resolve this issue.

**Comment by mach0** [comment]
beside the fact that this is the issue tracker for QGIS-Django which ist not related in any way to the plugin QuickOSM which i believe you mean - and without any further information anyway of the used QuickOSM Version and probably QGIS Version and the exact error you are getting I think there is less anyone can do here - but @Gustry should be the person to speak to .. closing this for now..
