### ISSUE TITLE
[FR]: zoom and data export for plugin statistics

### ISSUE THREAD

**Issue by jakimowb** [qgis/QGIS-Django#467]
### Feature Description

Thank you for the webpage re-design. The new plugin statistics are great!

However, I think they could be improved a bit by
- making the world map zoomable, e.g. added tools to zoom in / out and pan
- allowing developers to export the download statistics behind the map, e.g. to create own visualizations.
 
![grafik](https://github.com/user-attachments/assets/2fd712ce-9579-4174-b771-277d257a22aa)

**Comment by Xpirix** [comment]
Thank you @jakimowb, Transfered it to QGIS-Django as it is related to the plugins website.

**Comment by Xpirix** [comment]
Thanks for the ideas @jakimowb

I wanted to let you know that the plugin statistics feature is based on Metabase and we are limited to the existing features from them:

- For the Zoom/pan tools: This feature is not implemented yet, the issue has also been reported on the Metabase's repository: https://github.com/metabase/metabase/issues/33928.
- For the Export tools: This feature is already implemented (https://www.metabase.com/docs/latest/questions/sharing/exporting-results#exporting-results-of-a-dashboard-card), but it's only available if we use the Pro version (we are using the free version for now): https://www.metabase.com/docs/latest/permissions/data#download-results-permissions
