### ISSUE TITLE
Add new field for tools dependencies for the resource hub

### ISSUE THREAD

**Issue by Xpirix** [qgis/QGIS-Django#468]
From @jvdkwast

**Comment by jvdkwast** [comment]
For models (and maybe other items in the resource hub), it would be useful to add the dependencies on plugins, so the user knows what to install prior to using the model.
I suggest that for now, an extra field will be added to the metadata, but keep in mind the following workflow that would be nice in the future:

1. User creates a model with the graphical model builder.
2. Model builder stores automatically in the model file which providers were used.
3. The model is uploaded to the resource hub and the metadata field on dependencies is automatically extracted
4. The site and hub plugin by @ismailsunni can use the metadata on dependencies for filtering

**Comment by Xpirix** [comment]
Please find the proposed fix for this at #470

**Comment by jvdkwast** [comment]
Thanks. Looks good!
