### ISSUE TITLE
QuickMapServices - Only NASA and OSM

### ISSUE THREAD

**Issue by slyle-west** [qgis/QGIS-Django#472]
Only NASA and OSM show up as options under QuickMapServices in QGIS. I get the following error  when trying to get contributed pack:

"Error on getting contrib pack: 3"

**Comment by Xpirix** [comment]
I think it's better to report a specific plugin issue to its repository (https://github.com/nextgis/quickmapservices) because this repo is generally for the website plugins.qgis.org.
