### ISSUE TITLE
 Qgis  - Line direction histogram - Bug

### ISSUE THREAD

**Issue by SauloCar** [qgis/QGIS-Django#478]
Hello everyone,

I'm having an issue while trying to use the 'Line Direction Histogram' plugin in QGIS.

Traceback (most recent call last):
  
File "*****plugins\LineDirectionHistogram\linedirectionhistogram.py", line 125, in run
    self.dlg.progressBar.setValue(0.0)
TypeError: setValue(self, value: int): argument 1 has unexpected type 'float'

I have already tried modifying this line by replacing (0.0) with (0) and also changed it to int(xx), but I haven't had any success. Could someone help me?

Thank you very much.

**Comment by Xpirix** [comment]
Hello @SauloCar,

This repository is for the plugins' website (plugins.qgis.org). Could you report this issue to the plugin repo itself?
For the Line Direction Histogram, you can find the link to the repo at https://plugins.qgis.org/plugins/LineDirectionHistogram/#plugin-details. I think it's https://github.com/havatv/qgislinedirectionhistogramplugin.

Hope this helps.

Thanks.
