### ISSUE TITLE
Hub's projects size limitation

### ISSUE THREAD

**Issue by ErezSarig** [qgis/QGIS-Django#479]
Hi.
I'm failing to upload a gpkg with some scripts and tools to the QGiS [projects hub](https://plugins.qgis.org/geopackages/) because of a 1MB size limit. 
I really tried shaving it off or zip it in different ways but always came up with at least 1.5MB. I believe it's worth the few extra MB and I would hate not to publish it just because of this small size difference. Is it possible to raise the limitation to 2-3MB?

@Xpirix I was told you will be able to help me here :)

Thanks a lot. Erez Sarig

**Comment by Xpirix** [comment]
Hi @ErezSarig , Sure! I will take a look.

**Comment by ErezSarig** [comment]
I've uploaded it sucessfully. Thank you so much!
