### ISSUE TITLE
TUFLOW Unable to retrieve IFD Data

### ISSUE THREAD

**Issue by PJMichael00** [qgis/QGIS-Django#480]
Hi
Currently the TUFLOW Plugin is unable to extract data from ARR 2019 for the Rare Rainfall events. Trying to retrieve the Rare IFD data seem to cause the issue. Frequent and Infrequent seem to work OK.

Cheers
Paul

**Comment by Xpirix** [comment]
Hi @PJMichael00 ,

Please report specific plugin issues on the plugin's bug tracker/repository, as this repo is for the website. The link is available on each plugin details page either on QGIS or on the plugins.qgis.org website.
For the TUFLOW plugin, the link to the tracker is https://github.com/TUFLOW-Support/QGIS-TUFLOW-Plugin/issues.

Regards.
