### ISSUE TITLE
File does not exist error with gridding and other processes in QGIS

### ISSUE THREAD

**Issue by plovattsmith** [qgis/QGIS-Django#481]
GDAL command output:
ERROR 4: `file:///C:/etm2022cut.csv?type=csv&skipLines=1&maxFields=10000&detectTypes=yes&xField=lon&yField=lat&zField=emission&crs=EPSG:4326&spatialIndex=no&subsetIndex=no&watchFile=no' does not exist in the file system, and is not recognized as a supported dataset name.

The file path is: C:/etm2022cut.csv

Is this anything to do with the ? after the file name

**Comment by Xpirix** [comment]
Hi @plovattsmith,

Could you please report the issue in the QGIS repo (https://github.com/qgis/QGIS)? Please note that this repo is for the QGIS plugins website (plugins.qgis.org)

Regards.
