### ISSUE TITLE
Multilayer Select plugin

### ISSUE THREAD

**Issue by chuckcooper** [qgis/QGIS-Django#485]
When using the select by polygon feature, it doesn't select all points and lines within the polygon like it usually does.

**Comment by Xpirix** [comment]
Dear @chuckcooper 
This repository is dedicated solely to the QGIS Plugins Website (plugins.qgis.org). Please use the respective bug tracker for issues related to QGIS Desktop (https://github.com/qgis/QGIS).

Regards.
