### ISSUE TITLE
Be more explicit about "Server" checkbox in the plugin settings

### ISSUE THREAD

**Issue by Gustry** [qgis/QGIS-Django#487]
Given the page https://plugins.qgis.org/plugins/server/

![image](https://github.com/user-attachments/assets/249c7e18-5f88-4e49-997b-bf63a2fb2f1e)

I went to check a few plugins to look at their `__init__.py` file : 

* https://github.com/bsensix/VectorStats/blob/main/__init__.py
* https://github.com/nna-ina/gazetteer_creator/blob/master/__init__.py
* https://github.com/cyanlo/cyanlove/blob/main/__init__.py

They only define a `classFactory`, while a QGIS server plugin must define `serverClassFactory`, see the [docs](https://docs.qgis.org/3.34/en/docs/pyqgis_developer_cookbook/server.html#init-py)

My guess, it's that when they upload a new plugin, they don't know much about this checkbox : 
https://plugins.qgis.org/plugins/gazetteer_creator/update/

![image](https://github.com/user-attachments/assets/f70a255e-fe11-46cf-b4d9-e6d0ba8a0917)

Maybe a string or tooltip adding some information would be welcome.

> A server plugin is a plugin which can run on QGIS Server, by having a entrypoint `serverClassFactory`, see the [documentation](https://docs.qgis.org/3.34/en/docs/pyqgis_developer_cookbook/server.html#writing-a-server-plugin).

I'm not sure if it's quick to add a check when a version is uploaded.

**Comment by Xpirix** [comment]
Hi @Gustry 

Please find the proposed fix at #490. About the check, do you mean a blocking error that arises whenever the server attribute is set to True in the metadata, but the entry point serverClassFactory doesn't exist in __init.py__ file?
If so, I think it would change the workflow of the plugin. Perhaps we should let others know before. What do you think?

**Comment by Gustry** [comment]
Thanks @Xpirix for your fix.

I was jsut wondering the same question as in #494 if the flag in the `metadata.txt` should be prioritize versus the one in the plugin settings.

I'm not sure what is the workflow under the hood about this flag which can be set in two different places.

**Comment by Xpirix** [comment]
You're welcome @Gustry.

Replied at https://github.com/qgis/QGIS-Django/pull/494#issuecomment-2516190256
