### ISSUE TITLE
Owners cannot approve plugins?

### ISSUE THREAD

**Issue by carolinux** [qgis/QGIS-Django#49]
Hi, I wonder what is the purpose of the code being like this here:
https://github.com/qgis/QGIS-Django/blob/master/qgis-app/plugins/views.py#L156
and here:
https://github.com/qgis/QGIS-Django/blob/master/qgis-app/plugins/models.py#L263

ie, why would somebody who is an owner of a plugin, need additional permissions to be able to approve said plugin?

**Comment by elpaso** [comment]
You might find an answer here: https://github.com/qgis/QGIS-Django/blob/master/qgis-app/plugins/models.py#L254

**Comment by carolinux** [comment]
I am asking what is the thought behind this - why an owner is not a de facto approver?

**Comment by elpaso** [comment]
Because to approve a plugin you need to be a `trusted` user **and** an editor for that plugin. This was decided long time ago (not by me!), if you want to discuss this topic, the dev list is probably the right place.

**Comment by anitagraser** [comment]
It's a quality & safety check which should be performed by someone other
than the plugin dev. For background info, maybe have a look at the "trusted
plugins" post on blog.qgis.org

**Comment by carolinux** [comment]
http://blog.qgis.org/2016/08/26/what-are-trusted-plugins/ 
great, makes sense. 

BTW (related to this repository, no action or further comment requested - just putting it here in case it's helpful because there's a FIXME) - there was must have been some bug in the website which had let me approve plugins for a long time now without the correct permissions(last date being April 20, 2016)  and now I can't (which is why I was a bit confused) . I suppose the change fixing that is this:
https://github.com/qgis/QGIS-Django/commit/9957264e621dc7fb3ac84668818d2105fa8d5d1d

Indeed the widget was not disabled for me in the past. 

```if instance and not is_trusted:``` 
would not evaluate to True if instance was None for some reason... Maybe that's related to the problem.
