### ISSUE TITLE
Can't download plugins

### ISSUE THREAD

**Issue by ksketo** [qgis/QGIS-Django#50]
I am running QGIS on docker and I noticed that I can't install plugins. Every time I was getting a network timeout error. Initially, I thought that this was related to a bug with the docker image, but when I tried to access the download link on the browser I also got a network error. These are the links that I tried and both failed:
- http://plugins.qgis.org/plugins/openlayers_plugin/version/1.4.1/download/?qgis=2.14
- http://plugins.qgis.org/plugins/qgis2web/version/1.19.0/download/

**Comment by akbargumbira** [comment]
I can download both plugins just fine

**Comment by ksketo** [comment]
It was due to the network. Was fixed when I connected to a different network.
