### ISSUE TITLE
Plugin notifications sent to dev list are bounced and returned to noreply@qgis.org

### ISSUE THREAD

**Issue by rduivenvoorde** [qgis/QGIS-Django#52]
@pcav kept receiving email notifications from the plugin website.

Apparent the reason is:
- the applications is sending all these notifications to all 'staff' members/users AND(!) to the QGIS_DEV_MAILING_LIST_ADDRESS
- then these posts are bounced (because of too many recepients?), and returned to... noreply@qgis.org (the default FROM-address)
- this email addres is currently then sent to this group with: @pcav @timlinux @g-sherman and @elpaso 

We think that sending to the dev list is not needed (as currently apparently nobody missed it).

Looking at https://github.com/qgis/QGIS-Django/blob/master/qgis-app/plugins/views.py 
It appears that if we remove the different lines of:
`recipients.append(settings.QGIS_DEV_MAILING_LIST_ADDRESS)`
only staff members will receive these mailings.

@elpaso what you think? Ok if I add a PullRequest for that?

**Comment by jef-n** [comment]
sorry, already changed in 7f3b6fde3

**Comment by elpaso** [comment]
@jef-n did you also deploy the changes?

**Comment by jef-n** [comment]
@elpaso yes.
