### ISSUE TITLE
Upgrade project to Django 4/Python 3.7+?

### ISSUE THREAD

**Issue by brylie** [qgis/QGIS-Django#54]
Django 2.0 was recently released. What are tasks related to upgrading this project to support Django 2.0/Python 3.6+? How may I help?

**Comment by lhirlimann** [comment]
@dimasciput  was this achieve with the plugin migration ?

**Comment by DelazJ** [comment]
According to https://github.com/qgis/QGIS-Django/blob/master/REQUIREMENTS.txt, Django version is 2.2.5
Closing?
