### ISSUE TITLE
Deprecate plugins.qgis.org/planet/ URL

### ISSUE THREAD

**Issue by kannes** [qgis/QGIS-Django#56]
qgis.org/planet/ redirects to planet.qgis.org/planet/ so that seems to be the canonical URL.
Please make plugins.qgis.org/planet/ also redirect there. Otherwise it is just confusing. The plugins subdomain is currently the top result on Google for "qgis planet" which is looking weird.

**Comment by lhirlimann** [comment]
@dimasciput can you have a look ? or tell me where to look , and maybe add wiki entries somewhere so we know how this is configured and works ?
 Cloudflare is not happy with those 2 first URLs : planet.qgis.org/planet/ and qgis.org/planet/

**Comment by DelazJ** [comment]
Afaics, planet.qgis.org/planet/ currently opens qgis.org and qgis.org/planet/ returns 404. plugins.qgis.org/planet/ however opens the planet page...

**Comment by Xpirix** [comment]
Hello everyone,

Currently, both planet.qgis.org/planet/ and qgis.org/planet/ return 404. Only plugins.qgis.org/planet/ returns the planet page as mentioned in the previous comment. It is still the top result on Google.

Kind Regards,
