### ISSUE TITLE
Update download URLS to https in the db

### ISSUE THREAD

**Issue by kannes** [qgis/QGIS-Django#57]
https://github.com/qgis/QGIS-Django/blob/master/scripts/get_plugins_xml replaces http with https in the <download_url> tags. Shouldn't this be done in the db or where ever it is stored once and for all ?

**Comment by elpaso** [comment]
no: the URL is not in the DB but generated dynamically: in theory, it should return https if the original call was secure, http if not.
But you are right that this is currently broken, probably by some docker/nginx misconfiguration on the server.

**Comment by timlinux** [comment]
Can you provide a specific case where http instead of https is being used in the xml or elsewhere in the site?

**Comment by kannes** [comment]
Sorry, I don't remember anything about this.
