### ISSUE TITLE
rotate tmp/planet_update.log

### ISSUE THREAD

**Issue by elpaso** [qgis/QGIS-Django#59]

**Comment by lhirlimann** [comment]
@timlinux looking at the code I only find comments about how the log file is generated.
I'd like to add a logrotate cron job to fix this issue. Where should I look ?

**Comment by sumandari** [comment]
Hi @lhirlimann, 
FYI, there's already a cron job in server runs every 10 minutes for feedjackupdate
`python manage.py feedjackupdate`

**Comment by timlinux** [comment]
@dimasciput implementation of feedjack for django 2 uses a rancher scheduled task to update the feed and there are no logs kept, so we can close this.
