### ISSUE TITLE
Github is alerting this project that is has known vulnurabilities

### ISSUE THREAD

**Issue by rduivenvoorde** [qgis/QGIS-Django#61]
See:

https://github.com/qgis/qgis-django/network/alert/REQUIREMENTS.txt/django/open

Would be cool we find time to update Django etc

**Comment by lhirlimann** [comment]
what's the state of this, did we update django when we moved plugins ? cc @dimasciput  Is this a duplicate of https://github.com/qgis/QGIS-Django/issues/67 ?

**Comment by sumandari** [comment]
The [link](https://github.com/qgis/qgis-django/network/alert/REQUIREMENTS.txt/django/open) is broken, please consider this issue is no longer relevant.

**Comment by timlinux** [comment]
We still have warnings @sumandari 
![image](https://user-images.githubusercontent.com/178003/100856614-916afc80-3483-11eb-8079-842a4abd1299.png)


Let's keep our code clear of any known vulnerabilities.

**Comment by timlinux** [comment]
![image](https://user-images.githubusercontent.com/178003/100856761-bd867d80-3483-11eb-89bf-0fa4cef304ec.png)

**Comment by sumandari** [comment]
the alerts has been cleaned
![67_VCE_closed](https://user-images.githubusercontent.com/40058076/101101448-93f46000-3603-11eb-9f90-bd5bc8b0c4b8.png)

**Comment by DelazJ** [comment]
Should this issue report be closed, now?
