### ISSUE TITLE
[Feature Request] Warn when dev uploads a '__MACOSX' folder in the plugin zip

### ISSUE THREAD

**Issue by rduivenvoorde** [qgis/QGIS-Django#62]
See https://lists.osgeo.org/pipermail/qgis-developer/2019-March/056617.html

Some plugin zips contain a  '__MACOSX' folder which shows up in the plugin list:

![gnome-shell-screenshot-ETMGYZ](https://user-images.githubusercontent.com/731673/54188128-6078b600-44af-11e9-87d9-14c29cefe1fc.png)

We should either try not to show it in the list
Or warn the uploader when he/she uploads a zip with that folder

(I do not know what this folder contains or the sensitive data)

**Comment by rdbath** [comment]
I wrote a script to check for plugins with __macosx-folder:
https://gist.github.com/rdbath/7f617d4d3b3417fdb50ae9048e2056cc
The main parts could be also used to check files when user upload their plugins.

**Comment by sumandari** [comment]
@rduivenvoorde @thbaumann this validation was implemented in https://github.com/qgis/QGIS-Django/pull/116

**Comment by Xpirix** [comment]
Hello everyone,

I confirm the implementation of this validation as mentionned in the previous comment. It raises an error while uploading a plugin package that contains a '__MACOSX' folder.

Kind regards.

![Image](https://github.com/qgis/QGIS-Django/assets/43842786/8d42f68d-7a14-47f2-95fa-efa0afb39b52)
