### ISSUE TITLE
SVG is not loaded correctly on the website

### ISSUE THREAD

**Issue by Gustry** [qgis/QGIS-Django#65]
QuickOSM is using a SVG for the icon:
https://plugins.qgis.org/plugins/QuickOSM/
but the icon is not displayed anywhere on plugins.qgis.org.

On the featured list of plugins, if you scroll down a little, you will notice the missing icon too for QuickOSM:
https://plugins.qgis.org/plugins/featured/

SVG are working fine in Qt.

**Comment by Xpirix** [comment]
Dear @Gustry 

Please find at #348 the proposed fix for this issue.

Best regards
