### ISSUE TITLE
Planet does not work with some feeds

### ISSUE THREAD

**Issue by saberraz** [qgis/QGIS-Django#66]
I have noticed, that our feed does not get parsed correctly any more and it still shows old blog post. Here is the feed link:
https://www.lutraconsulting.co.uk/blog/categories/qgis/atom.xml

But planet shows older posts:
http://planet.qgis.org/planet/user/21/

**Comment by timlinux** [comment]
I think we can fix this now after I updated your URL right @saberraz ?

**Comment by saberraz** [comment]
Indeed. It is all sorted now. Thanks a lot for fixing the issue.
