### ISSUE TITLE
Please address CVE's

### ISSUE THREAD

**Issue by timlinux** [qgis/QGIS-Django#67]
@dimasciput it would be great to have a clean slate here: https://github.com/qgis/QGIS-Django/network/alerts

**Comment by sumandari** [comment]
@timlinux 
the [link](https://github.com/qgis/QGIS-Django/network/alerts) is broken, please consider this issue is no longer relevant.

**Comment by timlinux** [comment]
Duplicates #61  - I have given @sumandari needed access so she can address the CVE's

**Comment by sumandari** [comment]
the alerts has been cleaned
![67_VCE_closed](https://user-images.githubusercontent.com/40058076/101101249-22b4ad00-3603-11eb-90e7-86efb90feaf2.png)
