### ISSUE TITLE
Allow to create tokens to upload plugin

### ISSUE THREAD

**Issue by olivierdalang** [qgis/QGIS-Django#68]
Hi !

It would be nice if users could create plugin specific tokens usable instead of login with the plugin upload API endpoint. This would avoid having to potentially compromise OSGeo logins in the context of automated deployments (travis/github actions), and more generally open some more flexible collaboration possibilities.

Cheers !

Olivier

**Comment by Xpirix** [comment]
Hello,

It will probably require implementing [DRF Token Authentication](https://www.django-rest-framework.org/api-guide/authentication/#tokenauthentication) and eventually [DRF Simple JWT](https://pypi.org/project/djangorestframework-simplejwt/) into the application. 
After that, the user can get the token by making a request with his credentials from Curl or Postman for example.

Best regards,
Lova
