### ISSUE TITLE
The fields "create_date" and "update_date" both hold the same "update_date" in the plugin meta

### ISSUE THREAD

**Issue by suricactus** [qgis/QGIS-Django#69]
Literally the title. The problem is that the template model does not have access to the date of creation of the plugin, but only the date of creation of the version. Unfortunately, I'm not that familiar with Django to be able to solve it.

https://github.com/qgis/QGIS-Django/blob/33b7786e5201f14e9a80f512da9e76f7b94ad772/qgis-app/plugins/templates/plugins/plugins.xml#L17-L18

**Comment by suricactus** [comment]
I am just looking at the diff, the `create_date` and `modified_on` are still related only to the plugin version, but not to the plugin itself. In theory they would rarely have different values. I see this is a very ancient Django and this project barely lives, so I am sorry for causing you headaches. If it is possible to add the XML fields `plugin_create_date` and `plugin_update_date` I would be happy. The field `plugin_create_date` is the one that I actually need to sort the plugins in the Plugin manager (https://github.com/qgis/QGIS/pull/35008). The query should be something like this:

```
        SELECT DISTINCT ON (pv.plugin_id) pv.*,
        pv.created_by_id IN %(trusted_users_ids)s AS is_trusted,
		p.created_on AS plugin_created_on,
        p.modified_on AS plugin_modified_on
            FROM %(pv_table)s pv
            JOIN %{p_table}s p ON p.id = pv.plugin
            WHERE (
                pv.approved = True
                AND pv."max_qg_version" >= '%(qg_version)s'
                AND pv."min_qg_version" <= '%(qg_version)s'
                AND pv.experimental = %(experimental)s
            )
            ORDER BY pv.plugin_id, pv.version DESC
```
If it does not work, leave it, we can live without sorting the plugins by their initial release.

**Comment by elpaso** [comment]
@suricactus I'm sorry, but my time is very limited (you know how active I am on QGIS core). I'm not actively maintaining this project anymore, it's one of the oldest pieces of code of mines that is already running, sometimes I'm surprised it has been in production for so long without major issues.

**Comment by suricactus** [comment]
No problem, it is not that important. Better spend your time on the core :) .
Nevertheless, it's a pity it is in a such a sorry state. Are there any plans to replace/upgrade? I might have more free time after a month or two...
