### ISSUE TITLE
Errors trying to update plugin

### ISSUE THREAD

**Issue by biglimp** [qgis/QGIS-Django#75]
Since the update last friday I cannot update one of my plugins ([1364] UMEP). The following error message is displayed:

**There were errors reading plugin package (please check also your plugin's metadata).
File is too big. Max size is 1048576 Bytes**

The plugin is attached. Is there a new size limit introduced?

[UMEP.zip](https://github.com/qgis/QGIS-Django/files/4914626/UMEP.zip)

**Comment by dimasciput** [comment]
@biglimp thanks, I'll look into it and see what is causing it.

**Comment by dimasciput** [comment]
Hi @biglimp, I increased the upload size limit, can you please try again?

**Comment by elpaso** [comment]
Note that keeping the upload limit low was a deliberate choice: the reason was that:
- we didn't want blobs or other big assets in the zip
- a plugin it's supposed to be mainly python code and icons and when compressed it should produce a very small zip

That is why the default values was so small, during the years it was increased though.

**Comment by dimasciput** [comment]
@elpaso ah ok got it, sorry I didn't know about that.

The past limit was 1048576 Bytes, and currently I've updated it to the size of the largest plugin available on the site which is 25mb. 
So should I set the limit back to the original?

**Comment by elpaso** [comment]
No, I also think that the default limit was too low (it was set a decade ago), I'm pretty sure that the limit we used in the old server had already been increased but I cannot remember what was its last value.

Anyway, you should probably go through the zips that are already uploaded on the server and get the max size, maybe something around 10MB would be good.

Also, make sure nginx limits are set accordingly.

**Comment by dimasciput** [comment]
@elpaso I already checked, and the largest size of the uploaded plugins is around 20mb, should I just set the max limit to 20mb?

**Comment by biglimp** [comment]
20 mb is fine. Thanks. I close this now.
