### ISSUE TITLE
RSS feed for QGIS Planet

### ISSUE THREAD

**Issue by lucamanga** [qgis/QGIS-Django#79]
Please provide a RSS feed for QGIS Planet, as in old version
Thank you!

**Comment by lhirlimann** [comment]
this is a duplicate of https://github.com/qgis/QGIS-Django/issues/56 - feed should be working right now. cc @rduivenvoorde @dimasciput

**Comment by lhirlimann** [comment]
I would hav closed the issue but I don't have enough rights.

**Comment by rduivenvoorde** [comment]
fixed now
