### ISSUE TITLE
Links to QGIS Project blog posts in https://qgis.org/feeds/qgisplanet.atom news feed use http:// protocol instead of https://

### ISSUE THREAD

**Issue by agiudiceandrea** [qgis/QGIS-Django#85]
In the https://qgis.org/feeds/qgisplanet.atom news feed, the QGIS Project blog posts are linked using the http:// protocol instead of the https:// one.
The other blog posts in the same feed use the https:// protocol.

Please make the links to the QGIS Project blog posts use the https protocol, too.

**Comment by rduivenvoorde** [comment]
Not sure on how to do that. For blog.qgis.org we use a hosted wordpress instance.
In the Django Feedjack instance we indeed get the feed from
http://blog.qgis.org/feed/ (so NOT https)
But looking at the output of it, it does not become different if you request
httpS://blog.qgis.org/feed/

**Comment by agiudiceandrea** [comment]
Yes, the links are http:// right in the feed. So, how is the feed created? Maybe it Is the code in https://github.com/qgis/qgis-feed?

**Comment by timlinux** [comment]
@rduivenvoorde I think we can just change it here (needs admin rights): 

https://plugins.qgis.org/admin/feedjack/feed/28/change/?_changelist_filters=q%3Dqgis

![image](https://user-images.githubusercontent.com/178003/106590715-4fbf0680-6545-11eb-8c67-4abb51692c98.png)


I have set it to use https, not sure if it will re-havest old entries though.
